# Etapa 1: Compilar Angular
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build:prod


# Etapa 2: Configurar NGINX
FROM nginx:alpine


COPY nginx.conf /etc/nginx/nginx.conf


COPY --from=builder /app/dist/tracking-web/browser /usr/share/nginx/html

EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]